name: github_signin_aksoyhlc
description: "This package is made to make it easier for Flutter developers to add Github login/register to their applications. Official Github OAuth API used."
version: 0.0.4
homepage: https://github.com/Aksoyhlc/github_signin_aksoyhlc
documentation: https://github.com/Aksoyhlc/github_signin_aksoyhlc
issue_tracker: https://github.com/Aksoyhlc/github_signin_aksoyhlc/issues
repository: https://github.com/Aksoyhlc/github_signin_aksoyhlc



environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_inappwebview:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:


flutter:
